services:
  - type: web
    name: sistema-asistente-virtual
    env: python
    buildCommand: |
      cd "Sistema de asistencia virtual"
      pip install -r requirements.txt
    startCommand: |
      cd "Sistema de asistencia virtual"
      gunicorn -b 0.0.0.0:10000 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
